config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   root to: 'users#index'
   resources :users, only: [:index]do
      member do
         get :chat
      end
   end
  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.sent_messages.build(message_params)
    if @message.save
      redirect_to chat_user_path(@message.receiver_id)
    else
      flash[:error] = "Message failed to send."
      redirect_to chat_user_path(@message.receiver_id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:receiver_id, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search].present?
      @users = User.where("email LIKE ?", "#{params[:search]}%").where.not(id: current_user.id).order(:email)
    else
      @users = User.where.not(id: current_user.id).order(:email)
    end
    @users = @users.paginate(page: params[:page], per_page: 8)
  end

  def chat
    @user = User.find(params[:id])
    @messages = current_user.sent_messages
                            .where(receiver_id: @user.id)
                            .or(current_user.received_messages.where(sender_id: @user.id))
                            .includes(:sender)
                            .order(created_at: :asc)
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <div class="d-flex  align-items-center">
    <% if user_signed_in? %>
      Logged in as &nbsp;<strong><%= current_user.email %></strong>
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-success btn-sm mx-2' %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mx-2' %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm mx-2' %>
      <%= link_to "Login", new_user_session_path, class: 'btn btn-primary btn-sm mx-2' %>
    <% end %>
  </div>

  <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<% if message.sender == current_user %>
  <div class="message message-sent">
    <p style="text-align: right"><%= message.content %></p>
    <p style="text-align: right; font-size: x-small" ><%= message.created_at.strftime('%b %e, %Y at %I:%M %p') %></p>
  </div>
<% else %>
  <div class="message message-received">
    <p><%= message.content %></p>
    <p style="font-size: x-small"><%= message.created_at.strftime('%b %e, %Y at %I:%M %p') %></p>
  </div>
<% end %>


<style>
    .message {
        padding: 5px;
        margin-bottom: 10px;
        border-radius: 10px;
    }

    .message-sent {
        background-color: #c8def5;
        color: black;
    }

    .message-received {
        background-color: #f1f0f0;
        color: black;
    }

    .message-sent p {
        text-align: right;
        margin: 0;
    }

    .message-received p {
        margin: 0;
    }

</style>

app/views/users/chat.html.erb
<h2>Chat with <%= @user.email.split('@')[0].capitalize %></h2>

<!--Showing previous conversations-->
<%= render partial: "messages/message", collection: @messages %>
<!--End-->

<!--Composer to send messages-->
<%= form_with model: Message.new, url: messages_path, remote: true do |form| %>
  <div class="input-group mb-3">
    <%= form.hidden_field :receiver_id, value: @user.id %>
    <%= form.text_field :content, class: "form-control" %>
    <div class="input-group-append">
      <%= form.submit "Send", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<!--End-->
<br>
<%= link_to "Back to Users", users_path, class: "btn btn-secondary" %>


<style>
  h2{
      margin-top: 10px;
      margin-bottom: 20px;
  }
</style>

app/views/users/index.html.erb
<h2>Make a chat with your Friends!</h2>
<%= form_for(users_path, method: :get) do %>
  <div class="row">
    <div class="col-md-6">
      <%= text_field_tag :search, params[:search], class: "form-control form-control-sm", placeholder: "Search users" %>
    </div>
    <div class="col-md-6">
      <%= submit_tag "Search", class: "btn btn-primary btn-sm" %>
    </div>
  </div>
<% end %>
<% if @users.any? %>
  <br>
  <table class="table table-striped table-hover">
    <thead class="table table-dark">
    <tr>
      <th>User</th>
      <th>E-Mail</th>
      <th>Link</th>
      <% if params[:search].present? %>
        <th>Sent Messages</th>
        <th>Received Messages</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><strong><%= user.email.split('@')[0].capitalize %></strong></td>
        <td><%= user.email %></td>
        <td><%= link_to "Chat", chat_user_path(user), class: "btn btn-success btn-sm" %></td>
        <% if params[:search].present? %>
          <td><%= current_user.sent_messages.where(receiver_id: user.id).count %></td>
          <td><%= current_user.received_messages.where(sender_id: user.id).count %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No users available.</p>
<% end %>
<%= will_paginate @users %>


<style>
    h2 {
        margin-top: 10px;
        margin-bottom: 20px;
    }

    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .pagination a, .pagination span {
        padding: 10px;
        color: #333;
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 3px;
        margin-right: 5px;
        text-decoration: none;
        transition: all 0.2s ease;
    }

    .pagination a:hover, .pagination span.current {
        background-color: #333;
        color: #fff;
    }
</style>